version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      # Left in case I want to populate.
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # In case I don't have access to dbeaver or the like
  pgadmin:
    image: dpage/pgadmin4
    ports:
      # Worst Port I could think of to bind
      - 5150:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - database
    networks:
      # Use database as hostname to connect to postgres.
      - postgres-network
    volumes:
      # Don't forget to sudo chown -R 5050:5050 ./pgadmin-data
      # or else it will fail to bind
      - ./pgadmin-data/:/var/lib/pgadmin/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_HOST=database
      - NODE_ENV=production
      - PORT=8000
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
